spring:
  application:
    name: quantity-measurement-app
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

auth:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:180}
  oauth2:
    redirect-uri: ${FRONTEND_GOOGLE_REDIRECT}

app:
  cors:
    allowed-origin: ${FRONTEND_ORIGIN}

server:
  port: ${PORT:8080}

spring.config.import: optional:file:./secrets/oauth-secrets.properties[.properties]