DROP TABLE IF EXISTS quantity_measurement_history;

CREATE TABLE quantity_measurement_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    operation VARCHAR(50) NOT NULL,
    measurement_type VARCHAR(50),
    left_value DOUBLE,
    left_unit VARCHAR(50),
    left_measurement_type VARCHAR(50),
    right_value DOUBLE,
    right_unit VARCHAR(50),
    right_measurement_type VARCHAR(50),
    target_unit VARCHAR(50),
    result_value DOUBLE,
    result_unit VARCHAR(50),
    result_measurement_type VARCHAR(50),
    scalar_result DOUBLE,
    success BOOLEAN NOT NULL,
    error_message VARCHAR(512)
);

CREATE INDEX idx_quantity_measurement_history_operation ON quantity_measurement_history(operation);
CREATE INDEX idx_quantity_measurement_history_type ON quantity_measurement_history(measurement_type);
